-- ============================================================
-- 02_crear_secuencias.sql
-- ============================================================

CREATE SEQUENCE SEQ_USUARIOS  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ESPACIOS  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CLIENTES  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESERVAS  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUDITORIA START WITH 1 INCREMENT BY 1 NOCACHE;

-- Nuevas secuencias para las tablas ampliadas
CREATE SEQUENCE SEQ_PAGOS        START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HORARIOS     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DESCUENTOS   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EVALUACIONES START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NOTIFICACIONES START WITH 1 INCREMENT BY 1 NOCACHE;

-- Secuencia para tokens de evaluación por email
CREATE SEQUENCE SEQ_TOKENS_EVALUACION START WITH 1 INCREMENT BY 1 NOCACHE;

COMMIT;
